import Footer from "./components/Footer";
import Nav from "./components/Nav";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ weight: "400", preload: false });

export const metadata = {
    title: "Epic Games Store",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html style={inter.style} lang="en" className="bg-[#121212] min-w-[350px]">
            <body className="max-w-7xl mx-auto">
                <Nav />
                {children}
            </body>
            <Footer />
        </html>
    );
}
